version: '3.4'

services:
  clipuploader:
    image: ${DOCKER_REGISTRY-}clipuploader
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        AzureStorageConnectionString: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;
    build:
      context: .
      dockerfile: ClipUploader/Dockerfile
 ## azurite:
 ##   image: "mcr.microsoft.com/azure-storage/azurite"
 ##   container_name: azurite
 ##   ports:
 ##     - "10000:10000" 
 ##     - "10001:10001" 
 ##     - "10002:10002"
